name: tests-payments

on:
  pull_request:
    paths:
      - 'payments/**' #only for payments/ change

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #extract all codes
      - run: cd payments && npm install && npm run test:ci
