name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**' #only for orders/ change

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #extract all codes
      - run: cd orders && npm install && npm run test:ci
